### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by hanspnyholm** [frostefjell/eliq#13]
When Eliq site is down i got a lot of errors and the last line is.
urllib2.HTTPError: HTTP Error 400: Bad Request

**Comment by hanspnyholm** [comment]
The complete ertor message:

Traceback (most recent call last):
  File "eliq.py", line 15, in <module>
    data_now = eliq_online.get_data_now()
  File "/usr/local/lib/python2.7/dist-packages/eliqonline/api.py", line 110, in get_data_now
    eliqData = self._tools.get_data_from_eliq(function, parameters)
  File "/usr/local/lib/python2.7/dist-packages/eliqonline/tools.py", line 60, in get_data_from_eliq
    api_open = urllib.urlopen(api_url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 400: Bad Request

**Comment by frostefjell** [comment]
What should be thrown instead? 
Please see: issue #6

**Comment by hanspnyholm** [comment]
I have missed that I can do so. Thank you

**Comment by hanspnyholm** [comment]
My problem was that i run the script whitout channel id and thats have working before but not now.
So I added that, and runs well now.
You can delete this Error report
